[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pdf2text"
version = "0.0.1"
description = "Convert scanned PDF files to searchable text via Poppler and Tesseract"
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "pdf2image>=1.16",
    "pytesseract>=0.3",
    "Pillow>=10.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
pdf2text = "pdf2text.cli:main"
